### PR TITLE
Feature/335 implement atom number

### PR DESCRIPTION
**Pull request by Michel-Heinz**
I added a feature to display the numbers of the atoms in the stucture_customizer. This serves as a help to identify different atoms. 
One problem, due to Apple's lacking support for opengl upon first selecting the feature the programs takes quite some time to load (30ish seconds). There is no work around but a complete change of strategy to display those numbers. However, this only takes so long for the first time, afterwards even after restarting the program or rebooting the computer, it is instantaneous.

### CODE REVIEW

**Comment by Michel-Heinz** [comment]
I improved the overall test coverage to above 75% in this branch :)

**Comment by adrianusler** [comment]
Could we handle this by fake-activating the feature once during installation @Michel-Heinz?

**Comment by Michel-Heinz** [comment]
@ab5424 Yes that it the expected behavior else switching to stick mode would not work

**Comment by Michel-Heinz** [comment]
@adrianusler I had the same idea, however I do not know if that would be best and i wouldn t know how to do it

**Comment by ab5424** [comment]
@Michel-Heinz @adrianusler Then I'd prefer this to be merged, we can open an issue about the problems on macOS

**Review by ab5424 — APPROVED** [review]

**Review by adrianusler — APPROVED** [review]

**Comment by adrianusler** [comment]
Can you open the issue for macOS, @Michel-Heinz ?

**Pull request merged**
