### PR TITLE
Add molara logo

### PR DESCRIPTION
**Pull request by Michel-Heinz**
I added the .svg and .png file of the molara logo to the repo. I excluded some codespell string. @ab5424  can you check that please?

### CODE REVIEW

**Comment by ab5424** [comment]
@Michel-Heinz `codespell` is ok. The png file look horrible for it's size though.

**Comment by Michel-Heinz** [comment]
> @Michel-Heinz `codespell` is ok. The png file look horrible for it's size though.

Yes it does I ll fix it

**Comment by Michel-Heinz** [comment]
The molara logo will now be displayed instead of the default python logo in the taskbar when using the program. I also refworked the logo for better resolution feel free to merge!

**Comment by Michel-Heinz** [comment]
@ab5424 this is read to merge. I propose we ignore the code cov, since the coverage is increased by this patch and we cannot test the main routine anyway, because we cannot close the program in tests due to the event loop.

**Comment by ab5424** [comment]
@Michel-Heinz For me it works on MacOS, but not on Windows (still shows the default python logo in the taskbar). I think this is a known problem: https://stackoverflow.com/questions/12432637/setting-the-windows-taskbar-icon-in-pyqt Shall we still merge and open a new issue or do you want to fix this now?

**Comment by Michel-Heinz** [comment]
I d like to merge now and fix this later on windows. I currently do not have a windows computer on hand.

**Comment by ab5424** [comment]
@Michel-Heinz You can use the Windows Cluster (https://help.itc.rwth-aachen.de/service/t4ibytwt1n3p/article/142725a3a4f14e4cbb0c66e00bacfbf7/), at least until 01. July when it will be discontinued.

**Comment by ab5424** [comment]
@Michel-Heinz The logo (and json files) are now included in the build, but there is still something missing when installing the wheel:
```

(Molara) alexbonkowski@182-151 Molara % molara examples/xyz/ferrocene.xyz                                      
Traceback (most recent call last):
  File "/Users/alexbonkowski/PycharmProjects/venv/Molara/bin/molara", line 8, in <module>
    sys.exit(main())
  File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/__main__.py", line 36, in main
    widget = MainWindow()
  File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/Gui/main_window.py", line 57, in __init__
    self.structure_customizer_dialog = StructureCustomizerDialog(self)
  File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/Gui/structure_customizer_dialog.py", line 43, in __init__
    self.update_settings_box()
  File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/Gui/structure_customizer_dialog.py", line 77, in update_settings_box
    for f in listdir(f"{self.src_path}/Settings/Structure")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/Settings/Structure'
```

**Comment by ab5424** [comment]
I assume this will be changed anyway when we shift the settings file to home?

**Review by ab5424 — APPROVED** [review]
@Michel-Heinz I'm fine with merging now, but the problem with the build needs to be addressed before a new release.

**Comment by adrianusler** [comment]
> @Michel-Heinz The logo (and json files) are now included in the build, but there is still something missing when installing the wheel:
> 
> ```
> 
> (Molara) alexbonkowski@182-151 Molara % molara examples/xyz/ferrocene.xyz                                      
> Traceback (most recent call last):
>   File "/Users/alexbonkowski/PycharmProjects/venv/Molara/bin/molara", line 8, in <module>
>     sys.exit(main())
>   File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/__main__.py", line 36, in main
>     widget = MainWindow()
>   File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/Gui/main_window.py", line 57, in __init__
>     self.structure_customizer_dialog = StructureCustomizerDialog(self)
>   File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/Gui/structure_customizer_dialog.py", line 43, in __init__
>     self.update_settings_box()
>   File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/Gui/structure_customizer_dialog.py", line 77, in update_settings_box
>     for f in listdir(f"{self.src_path}/Settings/Structure")
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/Settings/Structure'
> ```

@ab5424 So should we include a check if the directory exists and let Molara create the directory if it doesn't exist?
If so, where should we do that? Upon program startup?

**Comment by adrianusler** [comment]
When I open the program, I get the error
`Ignoring window icon 10339954 exceeds maximum xcb request length 4194303`
And this error keeps coming up whenever I click a menu item.

**Comment by ab5424** [comment]
> When I open the program, I get the error `Ignoring window icon 10339954 exceeds maximum xcb request length 4194303` And this error keeps coming up whenever I click a menu item.

Which OS?

**Comment by ab5424** [comment]
> > @Michel-Heinz The logo (and json files) are now included in the build, but there is still something missing when installing the wheel:
> > ```
> > 
> > (Molara) alexbonkowski@182-151 Molara % molara examples/xyz/ferrocene.xyz                                      
> > Traceback (most recent call last):
> >   File "/Users/alexbonkowski/PycharmProjects/venv/Molara/bin/molara", line 8, in <module>
> >     sys.exit(main())
> >   File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/__main__.py", line 36, in main
> >     widget = MainWindow()
> >   File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/Gui/main_window.py", line 57, in __init__
> >     self.structure_customizer_dialog = StructureCustomizerDialog(self)
> >   File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/Gui/structure_customizer_dialog.py", line 43, in __init__
> >     self.update_settings_box()
> >   File "/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/site-packages/molara/Gui/structure_customizer_dialog.py", line 77, in update_settings_box
> >     for f in listdir(f"{self.src_path}/Settings/Structure")
> > FileNotFoundError: [Errno 2] No such file or directory: '/Users/alexbonkowski/PycharmProjects/venv/Molara/lib/python3.9/Settings/Structure'
> > ```
> 
> @ab5424 So should we include a check if the directory exists and let Molara create the directory if it doesn't exist? If so, where should we do that? Upon program startup?

The settings should be stored in a user folder (ideally home), not in the python lib folder.

**Comment by adrianusler** [comment]
> Which OS?

Linux Mint

**Comment by adrianusler** [comment]
> The settings should be stored in a user folder (ideally home), not in the python lib folder.

But would we still have to make the check that I mentioned, or would the problem vanish once we moved the settings to home?

**Comment by ab5424** [comment]
> > The settings should be stored in a user folder (ideally home), not in the python lib folder.
> 
> But would we still have to make the check that I mentioned, or would the problem vanish once we moved the settings to home?

The folder (or file) only needs to be created when the user wants to use custom settings. Otherwise, default settings should be loaded from the program itself (and they should be hardcoded somewhere). There is no need to create the folder if only defauls are used.

**Comment by ab5424** [comment]
> When I open the program, I get the error `Ignoring window icon 10339954 exceeds maximum xcb request length 4194303` And this error keeps coming up whenever I click a menu item.

Sounds like the file is too large. Does not happen on windows or macos though (at least for me).

**Comment by adrianusler** [comment]
Where is the icon stored and how did you include it @Michel-Heinz?

**Comment by adrianusler** [comment]
> > When I open the program, I get the error `Ignoring window icon 10339954 exceeds maximum xcb request length 4194303` And this error keeps coming up whenever I click a menu item.
> 
> Sounds like the file is too large. Does not happen on windows or macos though (at least for me).

Right, I have decreased the size of the logo and now it also works for me. I hope everyone is fine with this workaround.

**Pull request merged**
