### PR TITLE
Add color scheme to structure customiser

### PR DESCRIPTION
**Pull request by Michel-Heinz**
I changed the color scheme back to jmol. It would be best if the structure customizer would allow to select the color scheme. Should we implement this before the new release or for the next one?

### CODE REVIEW

**Comment by ab5424** [comment]
@Michel-Heinz My original idea was that the user can choose the color scheme in the structure customiser, but I haven't worked with QTCreator yet. What do you think?

**Comment by ab5424** [comment]
@Michel-Heinz Sorry, didn't read your comment. I think it'd be best to implement the selection in the structure customiser, I see no benefit by just changing the default now.

**Comment by Michel-Heinz** [comment]
I ll get this done by Sunday

**Comment by Michel-Heinz** [comment]
I did it, you can now select between cpk and jmol

**Review by ab5424 — APPROVED** [review]

**Pull request merged**
