### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by ab5424**
Create `CODEOWNERS` file for extra security (branch protection). Pull requests have to be reviewed by at least one codeowner.

This could become more important in the future since we can also assign codeowners only submodules.

### CODE REVIEW

**Comment by adrianusler** [comment]
Can we exclude this file from the coverage report @ab5424?

**Comment by adrianusler** [comment]
> This could become more important in the future since we can also assign codeowners only submodules.

This sounds really intriguing! But there should always be a few global codeowners, right? Otherwise some parts of the code might become frozen at some point if someone implements a feature and then doesn't "show up" anymore.

**Comment by ab5424** [comment]
The four of us are global codeowners (hence the `*`).

**Comment by adrianusler** [comment]
You need someone to review this, @ab5424?

**Review by adrianusler — APPROVED** [review]

**Pull request merged**
