### PR TITLE
Increase coverage of aos.py

### LINKED ISSUE #446: Increase coverage of aos.py
aos.py wasn't really tested. Implement basic tests and add input file for more orbitals.

### PR DESCRIPTION
**Pull request by adrianusler**
I have extended the testing of the `calculate_aos()` routine.
Closes #446.

### CODE REVIEW

**Comment by ab5424** [comment]
@adrianusler `numpy` [advises against using `assert_array_almost_equal`](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_array_almost_equal.html), could you replace it?

**Comment by adrianusler** [comment]
> @adrianusler `numpy` [advises against using `assert_array_almost_equal`](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_array_almost_equal.html), could you replace it?

Done! Ready to merge now @ab5424 @Michel-Heinz

**Comment by ab5424** [comment]
Test failure is unrelated, merging @adrianusler

**Comment by ab5424** [comment]
@adrianusler @Michel-Heinz For context, the test on windows py3.12 are failing [because the corresponding `matplotlib 3.9.1` wheel was deleted from pypi](https://github.com/matplotlib/matplotlib/issues/28551)

**Comment by adrianusler** [comment]
> @adrianusler @Michel-Heinz For context, the test on windows py3.12 are failing [because the corresponding `matplotlib 3.9.1` wheel was deleted from pypi](https://github.com/matplotlib/matplotlib/issues/28551)

Thanks for letting us know, I thought at first that I had messed something up :sweat_smile:
Do you happen to know a way how we could fix this? Please excuse my lazy asking

**Comment by ab5424** [comment]
We could pin matplotlib to <3.9.1 but since this affects so many other projects as well (as you can see in the discussion linked above) I can only assume that they will fix this in the next days.

**Comment by tacaswell** [comment]
The 3.9.1 wheels on windows would, depending on import order, cause segfaults, see https://github.com/matplotlib/matplotlib/issues/28551#issuecomment-2266699619.

We deleted the bad wheels to avoid segfaults (which seemed like a good idea) but failed to anticipate that this would cause downstream projects to start trying to build mpl from source instead of pulling the 3.9.0 wheel.  We have now yanked the whole 3.9.1 release to fix these problems and will get 3.9.2 out as quick as we can.

To prevent this sort of thing in the future (trying to build something from source when you are not prepared to do so) I suggest using `matplotlib --only-binary "matplotlib" ` in your requirements file (which may be a good practice for all wheels that have extensions).

Sorry for the trouble.


-----

In general, if you want to pin to avoid a bad release, I suggest using `package!=X.Y.Z` (e.g. `matplotlib!=3.9.1` so that you do not have to remember to go back and remove the pin later.

**Pull request merged**
