### PR TITLE
Add .coord & _POSCAR suffix to example files

### PR DESCRIPTION
**Pull request by adrianusler**
The coord example files could not be opened because Molara didn't recognise a suffix. I have renamed them like this:
`coord1` -> `coord1.coord` etc.

In the long run, Molara should be able to handle cases where the suffix is missing, so this is not the perfect solution, but it solves the problem for now. We should not offer example files that cannot be opened...

### CODE REVIEW

**Comment by ab5424** [comment]
I'm not in favour of adding a suffix to the POSCAR files. They never have a suffix, when written by VASP.

**Comment by adrianusler** [comment]
> I'm not in favour of adding a suffix to the POSCAR files. They never have a suffix, when written by VASP.

Right, that's a good point. But then the importer code would have to be changed. It's definitely kind of awkward to offer a bunch of example files that cannot be opened...

**Comment by ab5424** [comment]
> > I'm not in favour of adding a suffix to the POSCAR files. They never have a suffix, when written by VASP.
> 
> Right, that's a good point. But then the importer code would have to be changed. It's definitely kind of awkward to offer a bunch of example files that cannot be opened...

Yes, I would really appreciate the possibility to manually select the file format, but I don't have the time to implement that atm.

**Comment by adrianusler** [comment]
@ab5424 Would names like `POSCAR_SrTiO3` or `SrTiO3_POSCAR` be ok as a quickfix?

**Comment by adrianusler** [comment]
> I guess so.

@ab5424 Do you prefer POSCAR_* or *_POSCAR?

**Comment by adrianusler** [comment]
I think this is now ready to merge @ab5424!

**Comment by ab5424** [comment]
My idea with the file names in the POSCAR folder was to cover different naming conventions and see if they all can be opened then with out importers.

**Comment by ab5424** [comment]
But I would be fine with merging this.

**Comment by adrianusler** [comment]
> My idea with the file names in the POSCAR folder was to cover different naming conventions and see if they all can be opened then with out importers.

Yes, and I think it's a good idea to have these in the public repo once Molara can actually cover these. Until then, we should just play around with the local files

**Review by Michel-Heinz — APPROVED** [review]

**Pull request merged**
