### PR TITLE
Use 1st party `uv` installation

### PR DESCRIPTION
**Pull request by ab5424**

### CODE REVIEW

**Review by adrianusler — COMMENTED** [review]
I am not sure what this Pull Request is about, @ab5424. Could you say a few words about it?

**Comment by ab5424** [comment]
@adrianusler We use `uv` to install packages instead of `pip` because it's much faster. This PR just changes it such that `uv` is not installed using `pip` but rather set up with a native github action. I haven't done a benchmark but this allows `uv` to store a cache so in principle this should make it another bit faster.

**Comment by Michel-Heinz** [comment]
Does this also impact the pip install molara command? when users install the package, or only the github actions?

**Comment by ab5424** [comment]
No, this is only to speed up testing/linting

**Comment by Michel-Heinz** [comment]
Feel free to merge when ready

**Review by Michel-Heinz — APPROVED** [review]

**Pull request merged**
