### PR TITLE
Feature/cube files visualization

### PR DESCRIPTION
**Pull request by Michel-Heinz**
I added the possibilty to display cube files. I also created a 3d surface object to inherit from when programming 3d surface visualization dialogs. I also added the possibility to chose the color of the surface to be displayed.

## Release Notes

- **New Features**
  - Introduced a 3D surface display option in the main interface.
  - Added functionality to import and process *.cube files.
  - New `VoxelGrid` class for managing voxel grid data.

- **Enhancements**
  - Updated UI components for better usability, including adjustments to dialog layouts and widget properties.
  - Improved handling of molecular orbital visualisation and surface rendering.

- **Bug Fixes**
  - Resolved issues related to the visualization of surfaces and color selection.

- **Tests**
  - Expanded test coverage for new features and modified existing tests to align with recent changes.

### CODE REVIEW

**Comment by Michel-Heinz** [comment]
@CodeRabbit review

**Comment by ab5424** [comment]
@Michel-Heinz Can you resolve the conflict?

**Review by ab5424 — APPROVED** [review]

**Comment by ab5424** [comment]
@Michel-Heinz Have you also looked at the "Outside diff range and nitpick comments" by coderabbit? I thought it had some good ideas about docstring enhancements etc.

**Comment by Michel-Heinz** [comment]
Can you give me some examples? I read through them, they were mostly about assertions if I remember correctly?

**Comment by ab5424** [comment]
image

**Comment by Michel-Heinz** [comment]
Yes you are right, those are good points. I neglected them for a reason, it would not consistent with our previous use of docstrings. However, I will take a look again and accept them. Now is as good a time as any to start using better docstrings.

**Pull request merged**
