### PR TITLE
Add cython-lint

### PR DESCRIPTION
**Pull request by ab5424**
@Michel-Heinz There seem to be a few unused imports and variables in the cython files, can they be safely removed?

`/Users/alexbonkowski/PycharmProjects/Molara/src/molara/Rendering/cylinder.pyx:108:14: 'i' defined but unused (try prefixing with underscore?)
/Users/alexbonkowski/PycharmProjects/Molara/src/molara/Rendering/cylinder.pyx:108:17: 'j' defined but unused (try prefixing with underscore?)
/Users/alexbonkowski/PycharmProjects/Molara/src/molara/Tools/raycasting.pyx:1:20: 'boundscheck' imported but unused
/Users/alexbonkowski/PycharmProjects/Molara/src/molara/Tools/raycasting.pyx:3:9: 'npc' imported but unused
/Users/alexbonkowski/PycharmProjects/Molara/src/molara/Tools/raycasting.pyx:23:17: 'j' defined but unused (try prefixing with underscore?)
/Users/alexbonkowski/PycharmProjects/Molara/src/molara/Tools/raycasting.pyx:24:40: 'sphere_origin' defined but unused (try prefixing with underscore?)
/Users/alexbonkowski/PycharmProjects/Molara/src/molara/Tools/raycasting.pyx:25:10: 'fl' defined but unused (try prefixing with underscore?)`

### CODE REVIEW

**Comment by Michel-Heinz** [comment]
For me the linting runs without any problems, have you already removed the variables?

**Comment by ab5424** [comment]
Yes

**Comment by Michel-Heinz** [comment]
So this can be merged after solving the conflicts

**Comment by Michel-Heinz** [comment]
What is this precommit.ci ? it fails on every branch

**Comment by ab5424** [comment]
> What is this precommit.ci ? it fails on every branch

It runs pre-commt on the repo (the idea is to automatically apply fixes from e.g. ruff format to the current branch if you forget to run pre-commit locally). It fails because of mypy, and it fails with the same errors as my local mypy so this is expected. I'm fine with merging, but someone needs to fix the errors (possibly in #321). I could do that but I'm not too familiar with the failing part of the code.

**Comment by Michel-Heinz** [comment]
Okay I ll have a look and I may ask @adrianusler to fix it.

**Pull request merged**
