### PR TITLE
Issue 372: logarithmic scaling of zoom factor

### PR DESCRIPTION
**Pull request by DariaBabushkina**
Added a logarithmic scaling of the zoom, so that it works properly with large systems.

### CODE REVIEW

**Comment by ab5424** [comment]
@DariaBabushkina I think you meant to request a merge into `main`and not my branch ([`housekeeping/pyright`](https://github.com/Molara-Lab/Molara/tree/housekeeping/pyright)), right?

**Comment by adrianusler** [comment]
Would it make sense to create a new pull request @ab5424 @DariaBabushkina? This one seems to be a bit messy because of the thing with the base branch

**Comment by DariaBabushkina** [comment]
I'll close this pull request for now and look into it. I am unsure whether I created the branch with a wrong base or sth happened in the meantime.

Sorry for the confusion! And thanks for the notice from both of you @ab5424 @adrianusler 

> Would it make sense to create a new pull request @ab5424 @DariaBabushkina? This one seems to be a bit messy because of the thing with the base branch

**Comment by adrianusler** [comment]
Just make a new Pull Request, @DariaBabushkina

**Comment by adrianusler** [comment]
I think nothing is wrong with your branch

**Comment by adrianusler** [comment]
Well done, @ab5424! I was wondering how this could be solved

**Comment by ab5424** [comment]
@DariaBabushkina I reverted all changes that came from my branch.

@adrianusler That's not the case, the branch was created from my branch so it included all changes I made. A new pull request won't fix this.

**Comment by adrianusler** [comment]
> @adrianusler That's not the case, the branch was created from my branch so it included all changes I made. A new pull request won't fix this.

Yes, I saw that when I also tried to make a "fresh" Pull Request and these commits kept showing up

**Comment by ab5424** [comment]
I did `git restore --source origin/main <filename>` on all affected files.

**Review by adrianusler — APPROVED** [review]

**Comment by adrianusler** [comment]
The zooming works much better now, @DariaBabushkina! Thanks for your contribution.

**Review by Michel-Heinz — APPROVED** [review]

**Comment by Michel-Heinz** [comment]
I tested this this morning and the zooming feels just perfect 👍

**Pull request merged**
