### PR TITLE
Use `uv` to install packages for testing workflow

### PR DESCRIPTION
**Pull request by ab5424**
Should be much faster than pip

### CODE REVIEW

**Comment by ab5424** [comment]
Tests now take half the time.

**Comment by Michel-Heinz** [comment]
Sound great, does this need any other dependencies, or does this only apply to the github workflow?

**Comment by ab5424** [comment]
This only applies to the github workflow.

**Comment by ab5424** [comment]
I think we don't need it in the linting workflow because there the installation time is not critical.

**Comment by ab5424** [comment]
Btw, uv does almist the same as pip but is faster since it is written in rust (see https://github.com/astral-sh/uv)

**Comment by Michel-Heinz** [comment]
Okay I ll merge then 👍

**Review by Michel-Heinz — APPROVED** [review]

**Pull request merged**
