### PR TITLE
Allow POSCARs without edge atoms

### LINKED ISSUE #416: Can't load POSCAR if no atoms are on a plane / edge
Fix: In `make_supercell`, only append `extra_atomic_nums` and `extra_fractional_coords` to the `atomic_nums` and `fractional_coords` arrays if these "extra" arrays are not empty!

### PR DESCRIPTION
**Pull request by ab5424**
Fixes #416

### CODE REVIEW

**Comment by ab5424** [comment]
@adrianusler Please merge

**Comment by adrianusler** [comment]
@ab5424 Right now, I cannot test the feature because the current Molara version doesn't run on my computer...

**Comment by ab5424** [comment]
Is there something beyond the `numpy` issue? If not, please downgrade `numpy`.

**Comment by adrianusler** [comment]
Yes, the numpy thing is just the tip of the iceberg, @ab5424

**Review by adrianusler — APPROVED** [review]

**Pull request merged**
